### ISSUE TITLE
Building a training set of tags for racket

### ISSUE THREAD

**Issue by iHiD** [exercism/racket#308]
Hello lovely maintainers :wave:

We've recently added "tags" to student's solutions. These express the constructs, paradigms and techniques that a solution uses. We are going to be using these tags for lots of things including filtering, pointing a student to alternative approaches, and much more.

In order to do this, we've built out a full AST-based tagger in C#, which has allowed us to do things like [detect recursion](https://exercism.org/tracks/csharp/exercises/collatz-conjecture/solutions?tags[]=technique:recursion) or [bit shifting](https://exercism.org/tracks/csharp/exercises/bob/solutions?tags%5B%5D=technique%3Abit-shifting). We've set things up so other tracks can do the same for their languages, but its a lot of work, and we've determined that actually it may be unnecessary. Instead we think that **we can use machine learning to achieve tagging with good enough results.** We've fine-tuned a model that can determine the correct tags for C# from the examples with a high success rate. It's also doing reasonably well in an untrained state for other languages. We think that with only a few examples per language, we can potentially get some quite good results, and that we can then refine things further as we go.

I released a new [video on the Insiders page](https://exercism.org/insiders) that talks through this in more detail.

We're going to be adding a fully-fledged UI in the coming weeks that allow maintainers and mentors to tag solutions and create training sets for the neural networks, but to start with, **we're hoping you would be willing to manually tag 20 solutions for this track**. In this post we'll add 20 comments, each with a student's solution, and the tags our model has generated. Your mission (should you choose to accept it) is to edit the tags on each issue, removing any incorrect ones, and add any that are missing. In order to build one model that performs well across languages, it's best if you stick as closely as possible to the C# tags as you can. Those are listed [here](https://exercism.org/docs/building/tooling/analyzers/tags). If you want to add extra tags, that's totally fine, but please don't arbitrarily reword existing tags, even if you don't like what Erik's chosen, as it'll just make it less likely that your language gets the correct tags assigned by the neural network.

---

To summarise - there are two paths forward for this issue:
1. **You're up for helping:** Add a comment saying you're up for helping. Update the tags some time in the next few days. Add a comment when you're done. We'll then add them to our training set and move forward.
2. **You not up for helping:** No problem! Just please add a comment letting us know :)

If you tell us you're not able/wanting to help or there's no comment added, we'll automatically crowd-source this in a week or so.

Finally, if you have questions or want to discuss things, it would be best done on the forum, so the knowledge can be shared across all maintainers in all tracks.

Thanks for your help! :blue_heart:

---

_Note: [Meta discussion on the forum](https://forum.exercism.org/t/maintainers-helping-us-build-training-data-for-tags/7974)_

**Comment by iHiD** [comment]
## Exercise: hello-world

### Code

```racket
#lang racket

(provide hello)
```

### Tags:
```text
construct:module
construct:provide
construct:racket
construct:tagged-value
paradigm:declarative
paradigm:functional
```

**Comment by iHiD** [comment]
## Exercise: bob

### Code

```racket
#lang racket

(provide response-for)

(require racket/string)

;; : string -> bool
(define (has-alpha? s)
  (for/or ([ch (string->list s)])
    (char-alphabetic? ch)))

;; : string -> bool
(define (shouting? s)
  (and (has-alpha? s)
       (string=? (string-upcase s) s)))

;; : string -> bool
(define (question? s)
  (string-suffix? s "?"))

;; : string -> bool
(define (silence? s)
  (string=? (string-trim s) ""))

;; : string -> string
(define (response-for inq)
  (cond
   [(shouting? inq) "Whoa, chill out!"]
   [(question? inq) "Sure."]
   [(silence? inq) "Fine. Be that way!"]
   [else "Whatever."]))
```

### Tags:
```text
construct:and
construct:char-alphabetic?
construct:char-upcase
construct:comment
construct:cond
construct:define
construct:for/or
construct:implicit-lifting
construct:invocation
construct:lambda
construct:list
construct:parameter
construct:provide
construct:string
construct:string=?
construct:string-suffix?
construct:string-trim
construct:variable-arity
paradigm:functional
paradigm:higher-order
technique:boolean-logic
technique:looping
uses:string-similarity
```

**Comment by iHiD** [comment]
## Exercise: hamming

### Code

```racket
#lang typed/racket

(define (hamming-distance [a : String] [b : String]) : Integer
  (if (or (empty? a)
          (empty? b))
      (error "Comparisons must be of equal length.")
      (if (or (= (string-length a) 0)
              (= (string-length b) 0))
          0
          (hamming-distance-iterator (string->list a) (string->list b) 0 0))))

;; Refactor to use (rest list) instead of tracking index
(define (hamming-distance-iterator [comparator : (Listof Char)]
                                   [candidate : (Listof Char)]
                                   [index : Integer]
                                   [distance : Integer]) : Integer
  (if (> index (- (length comparator) 1))
      distance
      (if (not (eq? (list-ref comparator index) (list-ref candidate index))) 
          (hamming-distance-iterator comparator candidate (+ 1 index) (+ 1 distance))
          (hamming-distance-iterator comparator candidate (+ 1 index) distance))))

(provide hamming-distance)
```

### Tags:
```text
construct:add
construct:boolean
construct:char
construct:comment
construct:define
construct:error
construct:if
construct:implicit-conversion
construct:index
construct:invocation
construct:lambda
construct:length
construct:list
construct:list-ref
construct:named-optional-parameter
construct:number
construct:optional-parameter
construct:parameter
construct:recursive-call
construct:string
construct:subtract
construct:typed-racket
construct:variable
construct:visibility
paradigm:functional
paradigm:imperative
paradigm:reflective
technique:exceptions
technique:higher-order-functions
technique:recursion
uses:List
```

**Comment by iHiD** [comment]
## Exercise: hamming

### Code

```racket
#lang racket

(require data/collection)

(provide hamming-distance)

;; Helpers

(define (point-distance a b)
  (if (char=? a b) 0 1))

;; Public API

(define hamming-distance
  (curry foldl (λ (sum a b) (+ sum (point-distance a b))) 0))

```

### Tags:
```text
construct:char
construct:comment
construct:curried-function
construct:define
construct:function
construct:if
construct:invocation
construct:lambda
construct:number
construct:parameter
construct:provide
construct:question-mark
construct:require
construct:string
construct:visibility-modifiers
paradigm:functional
paradigm:higher-order-functions
```

**Comment by iHiD** [comment]
## Exercise: scrabble-score

### Code

```racket
#lang racket

(provide score)

(require threading)

;; String -> Integer
;; sum up the integer scores of each character in string
(define (score word)
  (~> word
      string-upcase
      string->list
      (map get-score _)
      (apply + _)))

;; Char -> Integer
;; assign integer score to a character
(define (get-score c)
  (cond [(char-contains? "QZ" c) 10]
        [(char-contains? "JX" c) 8]
        [(char-contains? "K" c) 5]
        [(char-contains? "FHVWY" c) 4]
        [(char-contains? "BCMP" c) 3]
        [(char-contains? "DG" c) 2]
        [(char-contains? "AEIOULNRST" c) 1]
        [#t 0]))

;; String Char -> Boolean
;; return true if character is contained in string
(define (char-contains? s c)
  (~> s
      string->list
      (member c _)))
```

### Tags:
```text
construct:apply
construct:boolean
construct:char
construct:comment
construct:cond
construct:define
construct:function
construct:implicit-boolean-conversion
construct:implicit-conversion
construct:invocation
construct:lambda
construct:list
construct:map
construct:number
construct:parameter
construct:provide
construct:string
construct:underscore
construct:variable
construct:visibility
paradigm:functional
paradigm:reflective
technique:higher-order-functions
```

**Comment by iHiD** [comment]
## Exercise: roman-numerals

### Code

```racket
#lang racket
(define (roman-reducer n str)
    (cond
        [(>= n 1000) (roman-reducer (- n 1000) (string-append str "M"))]
        [(>= n 900) (roman-reducer (- n 900) (string-append str "CM"))]
        [(>= n 500) (roman-reducer (- n 500) (string-append str "D"))]
        [(>= n 400) (roman-reducer (- n 400) (string-append str "CD"))]
        [(>= n 100) (roman-reducer (- n 100) (string-append str "C"))]
        [(>= n 90) (roman-reducer (- n 90) (string-append str "XC"))]
        [(>= n 50) (roman-reducer (- n 50) (string-append str "L"))]
        [(>= n 40) (roman-reducer (- n 40) (string-append str "XL"))]
        [(>= n 10) (roman-reducer (- n 10) (string-append str "X"))]
        [(>= n 9) (roman-reducer (- n 9) (string-append str "IX"))]
        [(>= n 5) (roman-reducer (- n 5) (string-append str "V"))]
        [(>= n 4) (roman-reducer (- n 4) (string-append str "IV"))]
        [(>= n 1) (roman-reducer (- n 1) (string-append str "I"))]
        [else str]))

(define (to-roman n)
    (roman-reducer n ""))        

(provide to-roman)
```

### Tags:
```text
construct:string-append
construct:cond
construct:define
construct:function
construct:invocation
construct:lambda
construct:number
construct:parameter
construct:provide
construct:string
construct:subtract
construct:visibility-modifiers
paradigm:functional
paradigm:imperative
paradigm:object-oriented
technique:recursion
```

**Comment by iHiD** [comment]
## Exercise: phone-number

### Code

```racket
#lang racket

(provide numbers area-code pprint)

(define (area-code number)
  (substring (numbers number) 0 3))

(define (pprint number)
  (define fnumber (numbers number))
  (string-append "("                 
                 (substring fnumber 0 3)
                 ") "                 
                 (substring fnumber 3 6)
                 "-"
                 (substring fnumber 6)))

(define (numbers str)
  (define filtered-numbers
    (apply string
           (for/list ([c (in-string str)]
                      #:when (char-numeric? c))
             c)))    
  (match filtered-numbers
    [(and (app string-length 11) (regexp #rx"^1[:digit:]*"))
     (substring filtered-numbers 1)]
    [(app string-length 10)
     filtered-numbers]
    [else
     (build-string 10 (lambda _ #\0))]))
```

### Tags:
```text
construct:and
construct:apply
construct:build-string
construct:char
construct:char-numeric?
construct:define
construct:lambda
construct:list
construct:match
construct:number
construct:parameter
construct:pattern
construct:string
construct:string-append
construct:substring
construct:underscore
construct:use-value
construct:visibility
paradigm:functional
paradigm:reflective
technique:higher-order-functions
technique:pattern-matching
```

**Comment by iHiD** [comment]
## Exercise: nucleotide-count

### Code

```racket
#lang racket

(define (nucleotide-count nuc seq)
    (length (filter
        (lambda (c)
            (char=? c nuc))
        (string->list seq))))

(define (validate sequence)
    (define valid-nucs (string->list "ACTG"))
    (andmap 
        (lambda (n)
            (member n valid-nucs))
        (string->list sequence)))
            

(define (nucleotide-counts sequence)
    (if
        (not (validate sequence))
        (error "Invalid nucleotides")
        (list (cons #\A (nucleotide-count #\A sequence)) 
        (cons #\C (nucleotide-count #\C sequence)) 
        (cons #\G (nucleotide-count #\G sequence)) 
        (cons #\T (nucleotide-count #\T sequence)))))

(provide nucleotide-counts)
```

### Tags:
```text
construct:boolean
construct:char
construct:define
construct:error
construct:filter
construct:if
construct:invocation
construct:lambda
construct:list
construct:local-function
construct:parameter
construct:procedural
construct:string
construct:throw
construct:using-declarations
paradigm:functional
paradigm:imperative
paradigm:object-oriented
technique:exceptions
technique:higher-order-functions
```

**Comment by iHiD** [comment]
## Exercise: nucleotide-count

### Code

```racket
#lang racket

(provide nucleotide-counts)

(define-custom-hash-types char-hash
  #:key? char?
  char=?)

(define (nucleotide-counts str)
  (define tbl (make-mutable-char-hash '((#\T . 0) (#\G . 0) (#\C . 0) (#\A . 0))))
    
  (for ([c (in-string str)])
    (match c
      [(and key (or #\A #\C #\G #\T))
       (dict-update! tbl key add1)]
      [else
       (error "invalid nucleotide")]))
    
  (dict->list tbl))
```

### Tags:
```text
construct:boolean
construct:char
construct:custom-type
construct:define
construct:define-custom-hash-types
construct:error
construct:for-loop
construct:hash
construct:hash-table
construct:implicit-conversion
construct:invocation
construct:lambda
construct:list
construct:make-mutable-char-hash
construct:match
construct:number
construct:parameter
construct:pattern
construct:procedure
construct:provide
construct:racket
construct:string
construct:underscore
construct:variable-arity
paradigm:functional
paradigm:reflective
paradigm:declarative
paradigm:imperative
paradigm:object-oriented
technique:higher-order-functions
technique:looping
uses:HashTable
uses:MutableHashTable
```

**Comment by iHiD** [comment]
## Exercise: raindrops

### Code

```racket
#lang racket

(define (convert-prime num)
    (string-append
        (if (zero? (modulo num 3)) "Pling" "")
        (if (zero? (modulo num 5)) "Plang" "")
        (if (zero? (modulo num 7)) "Plong" "")))

(define (convert num)
    (let 
        ([converted (convert-prime num)])
        (if 
            (string=? "" converted) 
            (number->string num) 
            converted)))

(provide convert)
```

### Tags:
```text
construct:if
construct:implicit-conversion
construct:invocation
construct:lambda
construct:let
construct:number
construct:parameter
construct:provide
construct:string
construct:underscore
construct:variable-arity
paradigm:functional
paradigm:object-oriented
technique:higher-order-functions
```

**Comment by iHiD** [comment]
## Exercise: raindrops

### Code

```racket
#lang racket

(provide convert)

(require math/number-theory)

(define (convert n)
  (let ([r (foldl (lambda (x acc)
                    (string-append acc
                                   (cond [(= x 3) "Pling"]
                                         [(= x 5) "Plang"]
                                         [(= x 7) "Plong"]
                                         [else ""])))
                  ""
                  (divisors n))])
    (if (equal? r "")
        (number->string n)
        r)))
```

### Tags:
```text
construct:cond
construct:define
construct:else
construct:foldl
construct:if
construct:implicit-conversion
construct:invocation
construct:lambda
construct:let
construct:number
construct:number->string
construct:parameter
construct:provide
construct:string
construct:require
construct:variable-usage
paradigm:functional
paradigm:imperative
paradigm:object-oriented
technique:higher-order-functions
```

**Comment by iHiD** [comment]
## Exercise: allergies

### Code

```racket
#lang racket

(require threading)

(provide list-allergies allergic-to?)

(define allergies
  (make-hash
   '((1   "eggs")
     (2   "peanuts")
     (4   "shellfish")
     (8   "strawberries")
     (16  "tomatoes")
     (32  "chocolate")
     (64  "pollen")
     (128 "cats"))))

(define (allergic-to? t n)
  (if (member t (list-allergies n)) #t #f))

(define (list-allergies n)
  (flatten
   (foldl (lambda (e a)
            (if (> (bitwise-and n e) 0)
                (cons (hash-ref allergies e) a)
                a)) empty '(1 2 4 8 16 32 64 128))))
```

### Tags:
```text
construct:bitwise-and
construct:cons
construct:define
construct:empty
construct:foldl
construct:hash-table
construct:if
construct:lambda
construct:list
construct:make-hash
construct:number
construct:parameter
construct:provide
construct:racket
construct:require
construct:tuple
construct:using
construct:visibility-modifiers
paradigm:functional
paradigm:reflective
technique:bit-manipulation
technique:higher-order-functions
uses:HashTable
```

**Comment by iHiD** [comment]
## Exercise: two-fer

### Code

```racket
#lang racket

(provide two-fer)


(define (two-fer [name "you"])
  (format "One for ~a, one for me." name))

```

### Tags:
```text
construct:assignment
construct:default-argument-value
construct:function
construct:header
construct:lambda
construct:named-optional-argument
construct:optional-argument
construct:parameter
construct:provide
construct:string
construct:template-literal
construct:variable-usage
paradigm:functional
paradigm:imperative
paradigm:reflective
technique:higher-order-functions
```

**Comment by iHiD** [comment]
## Exercise: all-your-base

### Code

```racket
#lang racket

;(provide rebase)

(define (rebase list-digits in-base out-base)
  (reverse (rebase-out (base-ten list-digits in-base) out-base)))

(define (base-ten list-digits in-base)
  (define (base-ten-helper list-digits in-base result)
    (cond [(empty? list-digits) result]
          [else
           (base-ten-helper (rest list-digits) in-base (+ (* result in-base) (first list-digits)))]))
  (base-ten-helper list-digits in-base 0))

(define (rebase-out num out-base)
  (cond [(= num 0) empty]
        [else
         (cons (modulo num out-base) (rebase-out (floor (/ num out-base)) out-base))]))

(rebase (list 1 1 1 1 1 1 1 1) 2 10)
```

### Tags:
```text
construct:base-10-number
construct:comment
construct:cond
construct:cons
construct:define
construct:divide
construct:empty-list
construct:helper
construct:implicit-conversion
construct:invocation
construct:lambda
construct:list
construct:local-function
construct:multiply
construct:number
construct:parameter
construct:provide
construct:recursive-call
construct:reverse
construct:sexp
construct:template
construct:underscore
construct:visibility-modifiers
paradigm:functional
paradigm:reflective
technique:higher-order-functions
technique:recursion
uses:cons
```

**Comment by iHiD** [comment]
## Exercise: all-your-base

### Code

```racket
#lang racket
(require threading)

(provide rebase)

(define (rebase list-digits in-base out-base)
  (and~>
   list-digits
   (to-base-10 in-base)
   (from-base-10 out-base)))

;converts a list of digits to a number on base 10
(define (to-base-10 list-digits base)
  (cond
    [(<= base 1) false] 
    [(findf (lambda (digit) (or (>= digit base) (< digit 0))) list-digits) false] ;checks if any digit is outside of the valid range
    [else
     (let ([length-digits (length list-digits)])
       (~>>
        (* (list-ref list-digits i) (expt base (- length-digits i 1)))
        (lambda (i))
        (build-list length-digits)
        (foldl + 0)))]))

;converts a number to a list of digits in a specified base
(define (from-base-10 number base)
  (cond
    [(<= base 1) false]
    [(< number 0) false]
    [else
      (append (if
               (>= number base)
               (from-base-10 (quotient number base) base)
               '())
              (list (remainder number base)))]))
```

### Tags:
```text
construct:and
construct:append
construct:base-10-number
construct:boolean
construct:build-list
construct:char
construct:comment
construct:cond
construct:define
construct:else
construct:foldl
construct:if
construct:implicit-lambda
construct:invocation
construct:lambda
construct:let
construct:list
construct:list-ref
construct:logical-and
construct:logical-or
construct:number
construct:parameter
construct:procedural
construct:quotient
construct:recursive
construct:require
construct:string
construct:subtract
construct:threading
construct:to-base-10
construct:visibility
paradigm:declarative
paradigm:functional
paradigm:logical
paradigm:object-oriented
technique:boolean-logic
technique:higher-order-functions
technique:recursion
uses:append
uses:list
```

**Comment by iHiD** [comment]
## Exercise: armstrong-numbers

### Code

```racket
#lang racket

(require math srfi/1 srfi/26)

(provide armstrong-number?)

(define (armstrong-number? n)
  (define digits
    (unfold-right zero? (cut remainder <> 10) (cut quotient <> 10) n))
  (define pow (length digits))
  (= n (for/sum ([d digits]) (expt d pow))))
```

### Tags:
```text
construct:cut
construct:define
construct:for/sum
construct:function
construct:implicit-lifting
construct:invocation
construct:lambda
construct:length
construct:list
construct:number
construct:parameter
construct:provide
construct:quotient
construct:racket
construct:require
construct:sum
construct:unfold-right
construct:variable-arity
construct:visibility-modifiers
paradigm:functional
paradigm:reflective
technique:higher-order-functions
uses:math/srfi-1
uses:math/srfi-26
uses:unfold-right
```

**Comment by iHiD** [comment]
## Exercise: armstrong-numbers

### Code

```racket
#lang racket
(require threading)

(provide armstrong-number?)

(define (armstrong-number? n)
  (let ([digits (number->list n)])
    (~>
     (lambda (i) (expt i (length digits)))
     (map digits)
     (apply + _)
     (= n))))

(define (number->list n)
  (let-values ([(q r) (quotient/remainder n 10)])
    (flatten (list
              (if (positive? q) (number->list q) '())
              r))))
```

### Tags:
```text
construct:apply
construct:if
construct:lambda
construct:let
construct:let-values
construct:list
construct:map
construct:number
construct:parameter
construct:procedural
construct:quotient
construct:require
construct:underscore
construct:using
construct:visibility
paradigm:functional
technique:higher-order-functions
technique:recursion
```

**Comment by iHiD** [comment]
## Exercise: reverse-string

### Code

```racket
#lang racket
(require threading)

(provide my-reverse)

(define (my-reverse s)
  (~> s string->list
        reverse
        list->string))
```

### Tags:
```text
construct:function
construct:lang
construct:list
construct:module
construct:parameter
construct:provide
construct:require
construct:string
construct:threading
construct:use-library
construct:visibility
paradigm:functional
paradigm:reflective
technique:higher-order-functions
uses:string
```

**Comment by iHiD** [comment]
## Exercise: atbash-cipher

### Code

```racket
#lang racket

(define alphabet (range (char->integer #\a) (add1 (char->integer #\z))))

(define atbash-key (make-hash (map (lambda (a b) (cons (integer->char a)
                                                       (integer->char b))) alphabet (reverse alphabet))))

(define (group lst n)
  (let ([counter (let ([x 0])
                   (lambda (xx)
                     (begin0 x
                       (set! x (add1 x)))))])
    (group-by (lambda (x) (quotient (counter x) n)) lst)))

(define (encode m)
  (string-join
   (map list->string
        (group
         (filter-map (lambda (x)
                       (cond
                         [(char-numeric? x) x]
                         [(char-alphabetic? x)
                          (hash-ref atbash-key (char-downcase x))]
                         [#t #f]))
                     (string->list m)) 5))))

(define (decode m)
  (list->string
   (filter-map (lambda (x)
                 (cond
                   [(char-numeric? x) x]
                   [(char-alphabetic? x)
                    (hash-ref atbash-key x)]
                   [#t #f]))
               (string->list m))))

```

### Tags:
```text
construct:assignment
construct:begin
construct:char
construct:char->integer
construct:char-downcase
construct:cond
construct:construct
construct:filter-map
construct:hash
construct:hash-ref
construct:implicit-convert
construct:integer
construct:integral-number
construct:invocation
construct:lambda
construct:let
construct:let*
construct:list
construct:map
construct:number
construct:parameter
construct:quotient
construct:range
construct:set!
construct:string
construct:string-join
construct:variable-arity
paradigm:functional
paradigm:imperative
paradigm:reflective
technique:higher-order-functions
uses:Hash
```

**Comment by BNAndras** [comment]
I’ll take a look later this week.

**Comment by BNAndras** [comment]
Clean up existing tags

1. [ ] [hello-world](https://github.com/exercism/racket/issues/308#issuecomment-1788635463)
2. [ ] [bob](https://github.com/exercism/racket/issues/308#issuecomment-1788635575)
3. [ ] [hamming](https://github.com/exercism/racket/issues/308#issuecomment-1788635698)
4. [ ] [hamming](https://github.com/exercism/racket/issues/308#issuecomment-1788635818)
5. [ ] [scrabble-score](https://github.com/exercism/racket/issues/308#issuecomment-1788635943)
6. [ ] [roman-numerals](https://github.com/exercism/racket/issues/308#issuecomment-1788636055)
7. [ ] [phone-number](https://github.com/exercism/racket/issues/308#issuecomment-1788636173)
8. [ ] [nucleotide-count](https://github.com/exercism/racket/issues/308#issuecomment-1788636291)
9. [ ] [nucleotide-count](https://github.com/exercism/racket/issues/308#issuecomment-1788636406)
10. [ ] [raindrops](https://github.com/exercism/racket/issues/308#issuecomment-1788636516)
11. [ ] [raindrops](https://github.com/exercism/racket/issues/308#issuecomment-1788636671)
12. [ ] [allergies](https://github.com/exercism/racket/issues/308#issuecomment-1788636817)
13. [ ] [two-fer](https://github.com/exercism/racket/issues/308#issuecomment-1788636949)
14. [ ] [all-your-base](https://github.com/exercism/racket/issues/308#issuecomment-1788637077)
15. [ ] [all-your-base](https://github.com/exercism/racket/issues/308#issuecomment-1788637176)
16. [ ] [armstrong-numbers](https://github.com/exercism/racket/issues/308#issuecomment-1788637288)
17. [ ] [armstrong-numbers](https://github.com/exercism/racket/issues/308#issuecomment-1788637421)
18. [ ] [reverse-string](https://github.com/exercism/racket/issues/308#issuecomment-1788637535)
19. [ ] [atbash-cipher](https://github.com/exercism/racket/issues/308#issuecomment-1788637653)
20. [ ] [robot-name](https://github.com/exercism/racket/issues/308#issuecomment-1788637775)

Add new tags

1. [ ] [hello-world](https://github.com/exercism/racket/issues/308#issuecomment-1788635463)
2. [ ] [bob](https://github.com/exercism/racket/issues/308#issuecomment-1788635575)
3. [ ] [hamming](https://github.com/exercism/racket/issues/308#issuecomment-1788635698)
4. [ ] [hamming](https://github.com/exercism/racket/issues/308#issuecomment-1788635818)
5. [ ] [scrabble-score](https://github.com/exercism/racket/issues/308#issuecomment-1788635943)
6. [ ] [roman-numerals](https://github.com/exercism/racket/issues/308#issuecomment-1788636055)
7. [ ] [phone-number](https://github.com/exercism/racket/issues/308#issuecomment-1788636173)
8. [ ] [nucleotide-count](https://github.com/exercism/racket/issues/308#issuecomment-1788636291)
9. [ ] [nucleotide-count](https://github.com/exercism/racket/issues/308#issuecomment-1788636406)
10. [ ] [raindrops](https://github.com/exercism/racket/issues/308#issuecomment-1788636516)
11. [ ] [raindrops](https://github.com/exercism/racket/issues/308#issuecomment-1788636671)
12. [ ] [allergies](https://github.com/exercism/racket/issues/308#issuecomment-1788636817)
13. [ ] [two-fer](https://github.com/exercism/racket/issues/308#issuecomment-1788636949)
14. [ ] [all-your-base](https://github.com/exercism/racket/issues/308#issuecomment-1788637077)
15. [ ] [all-your-base](https://github.com/exercism/racket/issues/308#issuecomment-1788637176)
16. [ ] [armstrong-numbers](https://github.com/exercism/racket/issues/308#issuecomment-1788637288)
17. [ ] [armstrong-numbers](https://github.com/exercism/racket/issues/308#issuecomment-1788637421)
18. [ ] [reverse-string](https://github.com/exercism/racket/issues/308#issuecomment-1788637535)
19. [ ] [atbash-cipher](https://github.com/exercism/racket/issues/308#issuecomment-1788637653)
20. [ ] [robot-name](https://github.com/exercism/racket/issues/308#issuecomment-1788637775)

**Comment by ErikSchierboom** [comment]
_This is an automated comment_

Hello :wave: Next week we're going to start using the tagging work people are doing on these. If you've already completed the work, thank you! If you've not, but intend to this week, that's great! If you're not going to get round to doing it, and you've not yet posted a comment letting us know, could you please do so, so that we can find other people to do it. Thanks!

**Comment by BNAndras** [comment]
I made some initial progress, but COVID derailed me last week. I’ll keep reviewing but I doubt I’ll finish.

**Comment by ErikSchierboom** [comment]
Thanks for the help! We've updated the tags.
